### PR TITLE
Fix paint expansion issues

### PR DESCRIPTION
**Pull request by hanslovsky**
This branch/PR tries to find and fix the issue that causes #376 

Copied status report from https://github.com/saalfeldlab/paintera/pull/385#issuecomment-584892341:
I fixed the following issues:
 1. It was impossible to paint a single (data) voxel because the radius in data space was determined by ceiling the transformed radius, i.e. even if the transformed radius is small like `1e-10`, it would still end up being `1` instead of `0`, resulting in a `+`-shape. Fixed in 698e1013cdac6b126f1855cd713e4edd18d71f27
 2. Roi to be repainted in viewer was based on brush radius instead of actually painted voxels but because voxel have an extent, this may be incorrect, causing the "paint expansion" described in #376. Fixed in 63b546d820449e018cea1077a2aa3b4784dc39c8. When not axis-aligned, however, the repainted area is too small. While doing this, I also ensured that all viewers get updated, if appropriate, not just the one that is being painted in.

Additionally, I use optimized painting only if viewer is axis aligned with the data and the data is isotropic within the painting plane (550aa50cab8985b956a2e02746bd767b2cfccc6e). As a result, we do not need `HyperEllipsoidNeighborhood` and related classes anymore. Other than that, I decided to stick with the existing painting method because the small-radii issue in https://github.com/saalfeldlab/paintera/pull/385#issuecomment-584333693 is relevant only if the radius is in the order of the voxel size and I think the current behavior is ok for such corner cases.

### CODE REVIEW

**Comment by hanslovsky** [comment]
New findings in https://github.com/saalfeldlab/paintera/issues/376#issuecomment-584287460

**Comment by hanslovsky** [comment]
I am currently trying to 
 1. use the correct radii, and
 2. avoid the use of `HyperEllipsoidNeighborhood`.

(2) is simple: Use optimized painting, i.e. painting with neighborhoods in label space, only when axis-aligned **and** isotropic within the plane. However, there are some issues:
 - Some voxels are missed out sometimes (may be a bug with translating the center point and radius from world or viewer space to label coordinate space)
 - For small radii in label coordinate space, e.g. `1`, there will always be cases for which some voxel will not be painted even though they intersect with the brush overlay, e.g.
paintera-missing-intersecting-voxels
Maybe the optimized scheme should be abandoned alltogether.

There is, however, a performance issue: [Filling a transformed cylinder](https://github.com/saalfeldlab/paintera/blob/b975b81cfbfd5a073ca85bf48b0d53c223f9a809/src/main/java/org/janelia/saalfeldlab/paintera/control/paint/Paint2D.java#L97) does not seem to get the boundaries right and iterating over screen voxels is not efficient enough. This will require some more work.

**Comment by hanslovsky** [comment]
I fixed the following issues:
 1. It was impossible to paint a single (data) voxel because the radius in data space was determined by ceiling the transformed radius, i.e. even if the transformed radius is small like `1e-10`, it would still end up being `1` instead of `0`, resulting in a `+`-shape. Fixed in 698e1013cdac6b126f1855cd713e4edd18d71f27
 2. Roi to be repainted in viewer was based on brush radius instead of actually painted voxels but because voxel have an extent, this may be incorrect, causing the "paint expansion" described in #376. Fixed in 63b546d820449e018cea1077a2aa3b4784dc39c8. When not axis-aligned, however, the repainted area is too small. While doing this, I also ensured that all viewers get updated, if appropriate, not just the one that is being painted in.

Additionally, I use optimized painting only if viewer is axis aligned with the data and the data is isotropic within the painting plane (550aa50cab8985b956a2e02746bd767b2cfccc6e). As a result, we do not need `HyperEllipsoidNeighborhood` and related classes anymore. Other than that, I decided to stick with the existing painting method because the small-radii issue in https://github.com/saalfeldlab/paintera/pull/385#issuecomment-584333693 is relevant only if the radius is in the order of the voxel size and I think the current behavior is ok for such corner cases.

**Comment by hanslovsky** [comment]
@cpatrickc Please test this pull request whenever you have a minute and let me know what you think of the painting experience, in particular:
 1. Painting in high-resolution isotropic axis aligned both zoomed in/out
 2. Painting in low resolution anisotropic both zoomed in/out
 3. Painting non-axis aligned.

Let me know if you need help setting up your Paintera to use this branch.


Thank you!!

**Comment by igorpisarev** [comment]
This works great now! I tested different scenarios and everything worked as expected, and code looks good to me too.

**Comment by hanslovsky** [comment]
Thanks a lot @igorpisarev!

**Comment by cpatrickc** [comment]
I tested all scenarios outlined above. The brush works great!

**Comment by hanslovsky** [comment]
Great, thanks @cpatrickc

**Pull request merged**
