### PR TITLE
Bookmarks

### LINKED ISSUE #140: Add bookmarks
Like in BDV, enable storing and navigating to bookmarked viewer transforms.

### PR DESCRIPTION
**Pull request by hanslovsky**
Fixes #140
 - [x] add bookmark config
 - [x] add bookmark UIs
 - [x] add shortcuts to README
 - [x] serialize bookmarks into project file
 - ~[ ] add option to cancel applying bookmark and going back to previous state (within some time window)~
 - [x] add shortcut to go to bookmark (instead of going through UI)

Use these shortcuts to control bookmarks:
 -  `B`  Add bookmark with current global and 3D viewer transforms
 - `Shift` + `B` Open dialog to add bookmark with text note
 - `Ctrl`+`B` Open dialog to select bookmark

### CODE REVIEW

**Comment by hanslovsky** [comment]
Undoing bookmark selection within a short time window after selection should be worked on in a separate PR if it ever becomes an issue.

**Comment by igorpisarev** [comment]
Super-useful feature @hanslovsky!
Can you also add the bookmark actions as enum entries in one of the action types here (or as a new action type)?
https://github.com/saalfeldlab/paintera/tree/master/src/main/java/org/janelia/saalfeldlab/paintera/control/actions
And then check if the action is allowed in the predicate for the bookmark key shortcuts like this: https://github.com/saalfeldlab/paintera/blob/28cda971ee4c950b92472a28031eb3fdd4541b50/src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java#L379
This would disable the bookmark actions while in the shape interpolation mode, where it's important that the viewer transform doesn't change arbitrarily.

**Comment by hanslovsky** [comment]
@igorpisarev I added a new `NavigationActionType.Bookmark` `enum` entry and it seems to work as expected.

**Comment by hanslovsky** [comment]
I will go ahead and merge.

**Pull request merged**
