### PR TITLE
Remove obsolete interfaces and classes rebased

### LINKED ISSUE #379: Remove obsolete marker interfaces
There are a few interfaces that were used to indicate certain functionality that are still a remnant of when the viewer (and not the source) had the responsibility of creating and managing controls, UI elements, etc. Moving this responsibility into the sources made the sources more flexible and rendered those interfaces complete. We should remove those interfaces to avoid any further confusion.

See also #378

### PR DESCRIPTION
**Pull request by hanslovsky**
Same as #380 but rebased on master. Replaces #380

This PR is a draft to
 - [x] remove obsolete marker interfaces
   - [x] `HasHighlightingStreamConverter`
   - [x] `HasIdService`
   - [x] `HasLockedSegments`
   - [x] `HasMaskForLabel`
   - [x] `HasMeshCache`
   - [x] `HasMeshes`
   - [x] `HasSelectedIds`
   - [x] `HasFloodFillState`
   - [x] `HasFragmentSegmentAssignments`
   - [x] `HasAxisOrder`
 - [x] remove obsolete classes
   - [x] `Paintera` and helper classes for UI
   - [x] `AxisOrder`
   - [x] rename replacement classes appropriately, e.g. `Paintera2` -> `Paintera`
 - [x] move all kotlin files into `src/main/kotlin`

In the course of this clean-up, all handlers should be modified such that they use a specific source and do not request the current source from the viewer. The latter was necessary because all event handling and UI elements were managed by the viewer but with moving this responsibility into the individual sources, we can get rid of these hard-to-understand lines of code that query the viewer for the current source and check for many different interfaces.

This is a draft PR and it will probably take a while to update everything.

Fixes #379 and beyond

### CODE REVIEW

**Comment by hanslovsky** [comment]
This will be ready to merge after some usage testing.

**Comment by igorpisarev** [comment]
@hanslovsky Just tested and everything worked well for me too. Should be good to go?
Looks like after it's merged we would also need to remove Paintera2 from entry point configuration in https://github.com/saalfeldlab/paintera-cmd

**Comment by hanslovsky** [comment]
Thanks for testing @igorpisarev 
I just rebased on top of master and force pushed. I will talk to @cpatrickc before merging because he had reported an issue when committing a canvas.

**Comment by hanslovsky** [comment]
@cpatrickc Can you check if this PR still throws an exception whey commit a canvas? I rebased this PR on top of master, i.e. all commits in master are also contained in this PR branch:
```
git switch remove-obsolete-interfaces-and-classes-rebased
# if you already have the branch in your local repository, you will probably have to force pull because I rebased:
git pull --force
# you should see version 0.23.4-SNAPSHOT in the installation
mvn clean install
# Confirm the correct version (should be 0.23.4-SNAPSHOT-b79c0d559a6cb6aff3eda0cd27963a5aaa2f2380):
jgo -U org.janelia.saalfeldlab:paintera:0.23.4-SNAPSHOT+org.slf4j:slf4j-simple:1.7.2 --version
# Run without --version flag but with path to your project directory instead
jgo org.janelia.saalfeldlab:paintera:0.23.4-SNAPSHOT+org.slf4j:slf4j-simple:1.7.2
```

Let me know if you still have issues with committing the canvas.

Thanks

Phil

**Comment by hanslovsky** [comment]
@cpatrickc [reported](https://gitter.im/saalfeldlab/general?at=5e73e9231e369d63dff68cbf) that the canvas issue does not persist anymore. I will go ahead and merge.

**Pull request merged**
