### PR TITLE
Dataset discovery thread management and canceling

### LINKED ISSUE #160: dataset discovery threads stay alive after closing paintera
It is unclear why that happens and so far only observed with HDF5.

### LINKED ISSUE #167: Decouple LabelSourceStateDeserializer from N5
The `LabelSourceStateDeserializer` should be agnostic of N5. However, the following properties are being deserialized expecting an `N5DataSource`:
 - [x] `IdService`
 - [x] `FragmentSegmentAssignmentstate`
 - [x] `LabelBlockLookup`

Make sure that the fixes do not break existing paintera project files.

### LINKED ISSUE #168: Cannot deserialize projects that have HDF5 label sources
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ncsa.hdf.hdf5lib.exceptions.HDF5FileInterfaceException: File accessibilty:Unable to open file ["H5Fint.c line 1028 in H5F_open(): file is already open for read-only"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Fopen(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5F.H5Fopen(H5F.java:50)
	at ch.systemsx.cisd.hdf5.HDF5.openFileReadWrite(HDF5.java:203)
	at ch.systemsx.cisd.hdf5.HDF5BaseWriter.openFile(HDF5BaseWriter.java:215)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:147)
	at ch.systemsx.cisd.hdf5.HDF5BaseWriter.<init>(HDF5BaseWriter.java:147)
	at ch.systemsx.cisd.hdf5.HDF5WriterConfigurator.writer(HDF5WriterConfigurator.java:133)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.open(HDF5FactoryProvider.java:48)
	at ch.systemsx.cisd.hdf5.HDF5Factory.open(HDF5Factory.java:47)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Writer.<init>(N5HDF5Writer.java:92)
	at org.janelia.saalfeldlab.paintera.data.n5.N5HDF5Meta.writer(N5HDF5Meta.java:54)
	at org.janelia.saalfeldlab.paintera.data.n5.N5HDF5Meta.writer(N5HDF5Meta.java:10)
	at org.janelia.saalfeldlab.paintera.serialization.CommitCanvasN5Serializer.deserialize(CommitCanvasN5Serializer.java:36)
	at org.janelia.saalfeldlab.paintera.serialization.CommitCanvasN5Serializer.deserialize(CommitCanvasN5Serializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.janelia.saalfeldlab.paintera.data.mask.MaskedSourceDeserializer.deserialize(MaskedSourceDeserializer.java:74)
	at org.janelia.saalfeldlab.paintera.data.mask.MaskedSourceDeserializer.deserialize(MaskedSourceDeserializer.java:27)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.janelia.saalfeldlab.paintera.serialization.sourcestate.SourceStateSerialization$AbstractSourceStateDeserializer.deserialize(SourceStateSerialization.java:154)
	at org.janelia.saalfeldlab.paintera.serialization.sourcestate.SourceStateSerialization$SourceStateDeserializerWithoutDependencies.deserialize(SourceStateSerialization.java:199)
	at org.janelia.saalfeldlab.paintera.serialization.sourcestate.SourceStateSerialization$AbstractSourceStateDeserializer.deserialize(SourceStateSerialization.java:110)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.Gson.fromJson(Gson.java:967)
	at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer.makeStates(SourceInfoSerializer.java:156)
	at org.janelia.saalfeldlab.paintera.serialization.SourceInfoSerializer.populate(SourceInfoSerializer.java:96)
	at org.janelia.saalfeldlab.paintera.serialization.Properties.lambda$fromSerializedProperties$8(Properties.java:216)
	at org.janelia.saalfeldlab.util.MakeUnchecked.lambda$unchecked$4(MakeUnchecked.java:96)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:215)
	at org.janelia.saalfeldlab.paintera.serialization.Properties.fromSerializedProperties(Properties.java:142)
	at org.janelia.saalfeldlab.paintera.Paintera.lambda$startImpl$5(Paintera.java:203)
	at org.janelia.saalfeldlab.util.MakeUnchecked.lambda$function$2(MakeUnchecked.java:68)
	at java.util.Optional.map(Optional.java:215)
	at org.janelia.saalfeldlab.paintera.Paintera.startImpl(Paintera.java:203)
	at org.janelia.saalfeldlab.paintera.Paintera.start(Paintera.java:106)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Exception running application org.janelia.saalfeldlab.paintera.Paintera
```
Probably use `HDF5Writer` everywhere!

### PR DESCRIPTION
**Pull request by hanslovsky**
1. [x] Initialize the enclosing Thread as daemon Thread.
 2. [x] Discover datasets if and only if the selected directory is an actual N5 container, i.e. it contains an "n5":<version> attribute.
 3. [x] Stop discovery when OK or cancel buttons are pressed.

Fixes #160 
Fixes #167 
Fixes #168 in 43a844f

### CODE REVIEW

**Comment by hanslovsky** [comment]
As of 202d14a, only discovering datasets if the selected directory is a valid N5 container.

**Comment by hanslovsky** [comment]
Checked all tasks in the original coimment. Will test a little more before merging.

**Comment by hanslovsky** [comment]
Will merge this once `IdService` (de-)serialization is agnostic of N5 inside `LabelSourceState(De-)Serializer`.

**Comment by hanslovsky** [comment]
This should be good to merge now. I'd prefer to have it tested by other users, first, though.
@axtimwalde @bogovicj @constantinpape If you have a project lying around somewhere, please make a backup copy, then run this from paintera source root directory:
```
git fetch origin
git checkout -b dataset-discovery-threads-handling origin/dataset-discovery-threads-handling
mvn clean install
jrun org.janelia.saalfeldlab:paintera:0.8.2-SNAPSHOT+org.slf4j:slf4j-simple:1.7.25 /path/to/project
# save project and close paintera
jrun org.janelia.saalfeldlab:paintera:0.8.2-SNAPSHOT+org.slf4j:slf4j-simple:1.7.25 /path/to/project
```
`jrun` has been renamed to `jgo` recently. Replace `jrun` with `jgo` if necessary.
In the first run you should see warnings that deserialization for the id-service and assignments falls back to a legacy loader. Once you save the project and restart, these warnings should be gone and everything should still work as expected (assignments, id-service).

**Comment by hanslovsky** [comment]
I found out that the label-block-lookup serialization for N5 backend does not work. Will fix it.

**Comment by hanslovsky** [comment]
Fixed label-block-serialization in a8d4ae8

**Comment by constantinpape** [comment]
> I'd prefer to have it tested by other users, first, though.

@hanslovsky I tested it, works as you described it.
When opening the dataset the first time I get a lot of legacy loader warnings.
After save and reopening no more warnings and everything looks good.

**Comment by bogovicj** [comment]
@hanslovsky, this works for me as well.

**Comment by hanslovsky** [comment]
Thanks @bogovicj will merge and release!

**Pull request merged**
