### PR TITLE
Scale bar overlay

### LINKED ISSUE #238: Display scalebar in pantera
Bigdataviewer supports the option for a dynamic scalebar to be displayed based on the resolution values.
Is it possible to show this in paintera as well?

### PR DESCRIPTION
**Pull request by hanslovsky**
Add scale bar overlay to fix #238 

Still WIP but getting there.

 - [x] serialize scale bar settings (per project)
 - [x] select font size

### CODE REVIEW

**Comment by hanslovsky** [comment]
cc @constantinpape

**Comment by hanslovsky** [comment]
@constantinpape Feel free to try on this branch:
```
mvn clean install
jgo org.janelia.saalfeldlab:paintera:0.15.1-SNAPSHOT+org.slf4j:slf4j-simple:1.7.25
```

The `+org.slf4j:slf4j-simple:1.7.25` portion is for logging only and can be omitted.

**Comment by constantinpape** [comment]
Just tried it, looks great!

**Comment by hanslovsky** [comment]
Great, thank you. I just wanted to make sure that the scale bar looks accurate. It appeared so for me when comparing to individual voxels and to the size of the entire datasets, but it is always good to have a second pair of eyes double check.

**Comment by constantinpape** [comment]
> It appeared so for me when comparing to individual voxels and to the size of the entire datasets, but it is always good to have a second pair of eyes double check.

Yes, looked good to me too. However I haven't checked very closely.

Anyway, I will set this up to the collaborator who was interested in having this feature.
He will have a closer look and we will ifle an issue if we notice something funny on closer inspection.

**Comment by hanslovsky** [comment]
And it is available on conda (version 0.16.0) :)

**Pull request merged**
